name: check

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
      - name: Check script
        run: cargo fmt --check && cargo clippy --all-targets -- -D warnings && cargo test
